
export const testProfiles = {
    "PROFILE": [
        { name: "TOTAL BODY", price: 3000 },
        { name: "HEPATIC / LFT", price: 1200 },
        { name: "CARDIAC", price: 1500 },
        { name: "LIPID", price: 1000 },
        { name: "SMA – 12", price: 1400 },
        { name: "CORONARY / CARDIAC ENZYMES", price: 1800 },
        { name: "HYPERTENSION", price: 1100 },
        { name: "DIABETIC", price: 950 }
    ],
    "ROUTINE": [
        { name: "CBC/HAEMOGRAM", price: 500 },
        { name: "ESR", price: 150 },
        { name: "HB", price: 200 },
        { name: "PCV", price: 200 },
        { name: "BT.CT.PT.PTT", price: 300 },
        { name: "PLATELET COUNT", price: 250 },
        { name: "MALARIAL PARASITE", price: 300 },
        { name: "MICROFILARIA", price: 400 },
        { name: "URINE", price: 200 },
        { name: "STOOL", price: 250 }
    ],
    "SEROLOGY": [
        { name: "GROUP", price: 100 },
        { name: "RD ANTIBODY TITRE", price: 400 },
        { name: "DIRECT COOMB’S TEST", price: 500 },
        { name: "VDRL", price: 300 },
        { name: "HIV", price: 400 },
        { name: "WIDAL", price: 250 },
        { name: "PROTHROMBIN TIME", price: 350 },
        { name: "R A TEST", price: 300 },
        { name: "A S O", price: 300 },
        { name: "CRP", price: 300 },
        { name: "AUSTRALIA ANTIGEN", price: 450 },
        { name: "SEMEN", price: 800 },
        { name: "SPUTUM", price: 300 },
        { name: "MANTOUX’S TEST", price: 250 },
        { name: "URINE PREGNANCY TEST", price: 300 }
    ],
    "BIOCHEMISTRY": [
        { name: "BLOOD SUGAR F", price: 150 },
        { name: "BLOOD SUGAR PP", price: 150 },
        { name: "BLOOD SUGAR R", price: 150 },
        { name: "S. BILIRUBIN", price: 250 },
        { name: "S. G. O. T", price: 250 },
        { name: "S. G. P. T", price: 250 },
        { name: "S. ALKALINE PHOSPHATASE", price: 250 },
        { name: "S. LDH", price: 300 },
        { name: "S. URIC ACID", price: 250 },
        { name: "CALCIUM", price: 200 },
        { name: "S. PHOSPHORUS", price: 200 },
        { name: "BLOOD UREA", price: 250 },
        { name: "S. AMYLASE", price: 300 },
        { name: "S. PROTEINS", price: 300 },
        { name: "S. ELECTROLYTES", price: 350 },
        { name: "S. ACID PHOSPHATASE", price: 300 },
        { name: "S. CHOLESTEROL", price: 300 },
        { name: "S. HDL CHOL", price: 300 },
        { name: "S. LDL CHOL", price: 300 },
        { name: "S. TRIGLYCERIDES", price: 300 },
        { name: "S. CPK TOTAL", price: 400 },
        { name: "S. CK MB", price: 450 },
        { name: "GLYCOSYLATED HB", price: 600 },
        { name: "S. BICARBONATE", price: 300 },
        { name: "PLASMA AMMONIA", price: 400 },
        { name: "S. IRON, TIBC, % SAT", price: 600 }
    ],
    "BACTERIOLOGY": [
        { name: "CULTURE URINE", price: 600 },
        { name: "CULTURE STOOL", price: 600 },
        { name: "CULTURE PUS", price: 600 },
        { name: "CUL. THROAT SWAB", price: 500 },
        { name: "CULTURE BLOOD", price: 700 },
        { name: "CULTURE CSF", price: 700 },
        { name: "CSF/PERICARDIAL FL", price: 700 },
        { name: "ASCITIC /PLEURAL FL", price: 700 },
        { name: "T3 T4 TSH", price: 800 },
        { name: "LH FSH", price: 900 },
        { name: "PROLACTIN", price: 900 },
        { name: "BETA HCG", price: 1000 },
        { name: "TORCH", price: 1200 },
        { name: "CYTOLOGY", price: 1000 },
        { name: "HISTOPATHOLOGY", price: 1500 },
        { name: "WESTERN BLOT TEST", price: 2000 },
        { name: "ANY OTHER TEST", price: 500 }
    ]
};

export const allTests = Object.values(testProfiles).flat();
