
export const testProfiles = {
    "PROFILE": [
        { name: "A.N.C PROFILE", price: 1500 },
        { name: "BIOCHEMISTRY", price: 2500 },
        { name: "CARDIAC", price: 1500 },
        { name: "CORONARY / CARDIAC ENZYMES", price: 1800 },
        { name: "DIABETIC", price: 950 },
        { name: "HEPATIC / LFT", price: 1200 },
        { name: "HYPERTENSION", price: 1100 },
        { name: "LIPID", price: 1000 },
        { name: "TOTAL BODY", price: 3000 },
        { name: "TRIPLE-H", price: 1200 }
    ],
    "HAEMATOLOGY AND CLINICAL PATHOLOGY": [
        { name: "24 Hours Urinary Calcium", price: 300 },
        { name: "24 Hours Urinary Protein", price: 300 },
        { name: "ABSOLUTE EOSINOPHIL COUNT", price: 200 },
        { name: "AFB Stain", price: 150 },
        { name: "BT.CT.PT.PTT", price: 300 },
        { name: "Bone Marrow with Procedure", price: 1500 },
        { name: "CBC/HAEMOGRAM", price: 500 },
        { name: "Colony Count", price: 300 },
        { name: "Coomb's Test (Indirect)", price: 500 },
        { name: "Creatinine Clearance Test", price: 600 },
        { name: "ESR", price: 150 },
        { name: "Fungal Examination", price: 200 },
        { name: "G6-PD TEST", price: 400 },
        { name: "Gram Stain", price: 150 },
        { name: "HB", price: 200 },
        { name: "LE Cells", price: 250 },
        { name: "MALARIAL PARASITE", price: 300 },
        { name: "MICROFILARIA", price: 400 },
        { name: "Microalbumin (Urine)", price: 500 },
        { name: "PAP Stain", price: 500 },
        { name: "Pap Cytology Slide", price: 1500 },
        { name: "PCV", price: 200 },
        { name: "PLATELET COUNT", price: 250 },
        { name: "Porphobilinogen", price: 4000 },
        { name: "Retic Count", price: 150 },
        { name: "STOOL", price: 250 },
        { name: "Sickling Test", price: 150 },
        { name: "Stool Reducing Substance", price: 100 },
        { name: "Throat Swab Examination", price: 200 },
        { name: "URINE", price: 200 },
        { name: "Urine BS/BP (Bile Salts / Bile Pigments)", price: 80 },
        { name: "Urine Bence Jones Protein", price: 100 },
        { name: "Urine Microfilaria", price: 200 },
        { name: "Urine Protein / Creatinine Ratio", price: 600 },
        { name: "Urine Sugar (Specific)", price: 30 },
        { name: "Urobilinogen", price: 100 },
        { name: "Vaginal Swab Examination", price: 200 }
    ],
    "BIOCHEMISTRY": [
        { name: "24 HOURS URINARY VOLUME", price: 800 },
        { name: "ADA (Adenosine Deaminase)", price: 800 },
        { name: "ASCITIC TEST", price: 700 },
        { name: "BLOOD SUGAR R", price: 150 },
        { name: "BLOOD UREA", price: 250 },
        { name: "CALCIUM", price: 200 },
        { name: "FASTING BLOOD SUGAR(FBS)", price: 150 },
        { name: "Fasting C Peptide", price: 1300 },
        { name: "G.T.T (Glucose Tolerance Test)", price: 300 },
        { name: "GGTP (Gamma-GT)", price: 250 },
        { name: "GLYCOSYLATED HB", price: 600 },
        { name: "Ionised Calcium", price: 600 },
        { name: "Lipase", price: 450 },
        { name: "Magnesium", price: 600 },
        { name: "PLASMA AMMONIA", price: 400 },
        { name: "PP/PG/R BLOOD SUGAR", price: 150 },
        { name: "Protein Electrophoresis (Protein Epp)", price: 1000 },
        { name: "RENAL FUNCTIONAL TEST (RFT)", price: 1100 },
        { name: "S. ACID PHOSPHATASE", price: 300 },
        { name: "S. ALKALINE PHOSPHATASE", price: 250 },
        { name: "S. AMYLASE", price: 300 },
        { name: "S. BICARBONATE", price: 300 },
        { name: "S. BILIRUBIN", price: 250 },
        { name: "S. CHOLESTEROL", price: 300 },
        { name: "S. CK MB", price: 450 },
        { name: "S. CPK TOTAL", price: 400 },
        { name: "S. CREATININE", price: 250 },
        { name: "S. ELECTROLYTES", price: 350 },
        { name: "S. G. O. T", price: 250 },
        { name: "S. G. P. T", price: 250 },
        { name: "S. HDL CHOL", price: 300 },
        { name: "S. IRON, TIBC, % SAT", price: 600 },
        { name: "S. LDH", price: 300 },
        { name: "S. LDL CHOL", price: 300 },
        { name: "S. PHOSPHORUS", price: 200 },
        { name: "S. PROTEINS", price: 300 },
        { name: "S. TRIGLYCERIDES", price: 300 },
        { name: "S. URIC ACID", price: 250 },
        { name: "SMA – 12", price: 1400 },
        { name: "Spot Urine", price: 320 },
        { name: "Stone Analysis", price: 1000 }
    ],
    "HORMONES AND TUMOR MARKERS": [
        { name: "BETA HCG", price: 1000 },
        { name: "Beta Microglobulin", price: 1770 },
        { name: "CA-125", price: 1000 },
        { name: "CEA (Carcinoembryonic Antigen)", price: 900 },
        { name: "Cortisol", price: 800 },
        { name: "Free Thyroid Profile (FT3, FT4)", price: 750 },
        { name: "IgE Level", price: 1000 },
        { name: "LH FSH", price: 900 },
        { name: "PSA Free", price: 1000 },
        { name: "PSA Total", price: 850 },
        { name: "PROLACTIN", price: 900 },
        { name: "T3 T4 TSH", price: 800 },
        { name: "Total Testosterone", price: 800 }
    ],
    "SEROLOGY AND IMMUNOLOGY": [
        { name: "A S O", price: 300 },
        { name: "APLA (IgG / IgM)", price: 1000 },
        { name: "Anti CCP", price: 1350 },
        { name: "CRP", price: 300 },
        { name: "Chikungunya", price: 800 },
        { name: "D Dimer", price: 1200 },
        { name: "DIRECT COOMB’S TEST", price: 500 },
        { name: "Dengue IgG / IgM", price: 600 },
        { name: "Dengue NS1 Antigen", price: 600 },
        { name: "GROUP", price: 100 },
        { name: "HBsAg", price: 450 },
        { name: "HCV", price: 500 },
        { name: "HIV", price: 400 },
        { name: "HSCRP (High Sensitivity CRP)", price: 750 },
        { name: "Leptospira (IgG / IgM)", price: 700 },
        { name: "Lupus Anticoagulant", price: 2350 },
        { name: "MANTOUX’S TEST", price: 250 },
        { name: "NT Pro BNP", price: 2700 },
        { name: "PCT (Procalcitonin)", price: 2700 },
        { name: "PROTHROMBIN TIME", price: 350 },
        { name: "R A TEST", price: 300 },
        { name: "RD ANTIBODY TITRE", price: 400 },
        { name: "SEMEN", price: 800 },
        { name: "SPUTUM", price: 300 },
        { name: "Troponin T", price: 1000 },
        { name: "URINE PREGNANCY TEST", price: 300 },
        { name: "VDRL", price: 300 },
        { name: "WIDAL", price: 250 }
    ],
    "SPECIALIZED AND MOLECULAR": [
        { name: "Bactec Blood Culture", price: 1000 },
        { name: "Double Marker (Pregnancy)", price: 2200 },
        { name: "GeneXpert", price: 2700 },
        { name: "Quadraple Marker (Pregnancy)", price: 2800 }
    ],
    "BACTERIOLOGY / OTHER": [
        { name: "ANY OTHER TEST", price: 500 },
        { name: "ASCITIC /PLEURAL FL", price: 700 },
        { name: "CSF/PERICARDIAL FL", price: 700 },
        { name: "CUL. THROAT SWAB", price: 500 },
        { name: "CULTURE BLOOD", price: 700 },
        { name: "CULTURE CSF", price: 700 },
        { name: "CULTURE PUS", price: 600 },
        { name: "CULTURE STOOL", price: 600 },
        { name: "CULTURE URINE", price: 600 },
        { name: "CYTOLOGY", price: 1000 },
        { name: "HISTOPATHOLOGY", price: 1500 },
        { name: "WESTERN BLOT TEST", price: 2000 }
    ]
};

export const allTests = Object.values(testProfiles)
    .flat()
    .sort((a, b) => a.name.localeCompare(b.name));
